analytics: {}
color:
  brandColors:
    - '#C8D8C8'
    - '#083060'
    - '#78A8C0'
    - '#A04000'
    - '#C0D8E8'
  brandStrength: 0.183558
  lightness: 0.392723
  rhythmicContrast: 0.902027
  saturation: 0.796171
cta: {}
layout_spectrum: 1
name: FerieninNaplesfl
opengraph: {}
purpose: {}
typography_spectrum: 0.868243
