name: FerieninNaplesfl
favicon: null
layout_spectrum: 1
typography_spectrum: 0.868243
title: 'Ferien in Naples, Florida, USA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72808571-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8D8C8'
    - '#083060'
    - '#78A8C0'
    - '#A04000'
    - '#C0D8E8'
  brandStrength: 0.25
  lightness: 0.392723
  saturation: 0.875
  rhythmicContrast: 0.902027
purpose:
  - name: null
    item: null
    url: null
